language: python

python:
  - "2.7"
  - "3.6"

install:
  - if [ -d cache ]; then mv cache/* gwv/data/; fi
  - python setup.py install
  - pip install coverage
  - pip install codecov

script:
  coverage run -m unittest discover

after_success:
  codecov

cache:
  - directories:
    - cache

before_cache:
  - if [ ! -d cache ]; then mkdir cache; fi
  - mv gwv/data/cjksrc.json gwv/data/extf.json gwv/data/irg2015.json gwv/data/mj00501.json cache/
