language: python

python:
  - "2.7"
  - "3.6"

install:
  - python setup.py install
  - pip install coverage
  - pip install codecov

script:
  coverage run -m unittest discover

after_success:
  codecov
