language: python

python:
  - "2.7"
  - "3.6"

install:
  - if [ -d gwv_data_cache ] && [ -n "$(ls -A gwv_data_cache)" ]; then mv gwv_data_cache/* gwv/data/; fi
  - python setup.py install
  - pip install coverage
  - pip install codecov

script:
  coverage run -m unittest discover

after_success:
  codecov

cache:
  - directories:
    - gwv_data_cache

before_cache:
  - if [ ! -d gwv_data_cache ]; then mkdir gwv_data_cache; fi
  - mv gwv/data/cjksrc.json gwv/data/extf.json gwv/data/irg2015.json gwv/data/mj00501.json gwv_data_cache/
