language: python

python:
  - "3.8"

install:
  - pip install pyyaml
  - python -m bdat
  - pip install coverage
  - pip install codecov

script:
  coverage run -m unittest discover

after_success:
  codecov

cache:
  - directories:
    - gwv/data/3rd
